// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Internal.FantaSottone.Infrastructure.Models;

public partial class FantaSottoneContext : DbContext
{
    public FantaSottoneContext(DbContextOptions<FantaSottoneContext> options)
        : base(options)
    {
    }

    public virtual DbSet<GameEntity> GameEntity { get; set; }

    public virtual DbSet<PlayerEntity> PlayerEntity { get; set; }

    public virtual DbSet<RuleAssignmentEntity> RuleAssignmentEntity { get; set; }

    public virtual DbSet<RuleEntity> RuleEntity { get; set; }

    public virtual DbSet<UserEntity> UserEntity { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<GameEntity>(entity =>
        {
            entity.HasIndex(e => e.Status, "IX_GameEntity_Status");

            entity.HasIndex(e => e.UpdatedAt, "IX_GameEntity_UpdatedAt");

            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("sysutcdatetime()");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("sysutcdatetime()");

            entity.HasOne(d => d.CreatorPlayer).WithMany(p => p.GameEntityCreatorPlayer)
                .HasForeignKey(d => d.CreatorPlayerId)
                .HasConstraintName("FK_GameEntity_CreatorPlayer");

            entity.HasOne(d => d.WinnerPlayer).WithMany(p => p.GameEntityWinnerPlayer)
                .HasForeignKey(d => d.WinnerPlayerId)
                .HasConstraintName("FK_GameEntity_WinnerPlayer");
        });

        modelBuilder.Entity<PlayerEntity>(entity =>
        {
            entity.HasIndex(e => new { e.GameId, e.CurrentScore }, "IX_PlayerEntity_GameId_CurrentScore");

            entity.HasIndex(e => e.UserId, "IX_PlayerEntity_UserId");

            entity.HasIndex(e => new { e.GameId, e.UserId }, "UX_PlayerEntity_GameId_UserId_NotNull")
                .IsUnique()
                .HasFilter("([UserId] IS NOT NULL)");

            entity.Property(e => e.AccessCode).HasMaxLength(32);
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("sysutcdatetime()");
            entity.Property(e => e.UpdatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("sysutcdatetime()");
            entity.Property(e => e.Username).HasMaxLength(30);

            entity.HasOne(d => d.Game).WithMany(p => p.PlayerEntity)
                .HasForeignKey(d => d.GameId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_PlayerEntity_GameEntity");

            entity.HasOne(d => d.User).WithMany(p => p.PlayerEntity)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_PlayerEntity_UserEntity");
        });

        modelBuilder.Entity<RuleAssignmentEntity>(entity =>
        {
            entity.HasIndex(e => new { e.GameId, e.AssignedAt }, "IX_RuleAssignmentEntity_GameId_AssignedAt");

            entity.HasIndex(e => new { e.GameId, e.RuleId }, "IX_RuleAssignmentEntity_GameId_RuleId");

            entity.HasIndex(e => e.RuleId, "UX_RuleAssignmentEntity_RuleId").IsUnique();

            entity.Property(e => e.AssignedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("sysutcdatetime()");
            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("sysutcdatetime()");
            entity.Property(e => e.UpdatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("sysutcdatetime()");

            entity.HasOne(d => d.AssignedToPlayer).WithMany(p => p.RuleAssignmentEntity)
                .HasForeignKey(d => d.AssignedToPlayerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RuleAssignmentEntity_PlayerEntity");

            entity.HasOne(d => d.Game).WithMany(p => p.RuleAssignmentEntity)
                .HasForeignKey(d => d.GameId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RuleAssignmentEntity_GameEntity");

            entity.HasOne(d => d.Rule).WithOne(p => p.RuleAssignmentEntity)
                .HasForeignKey<RuleAssignmentEntity>(d => d.RuleId)
                .HasConstraintName("FK_RuleAssignmentEntity_RuleEntity");
        });

        modelBuilder.Entity<RuleEntity>(entity =>
        {
            entity.HasIndex(e => e.GameId, "IX_RuleEntity_GameId");

            entity.HasIndex(e => new { e.GameId, e.Name }, "UX_RuleEntity_GameId_Name").IsUnique();

            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("sysutcdatetime()");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("sysutcdatetime()");

            entity.HasOne(d => d.Game).WithMany(p => p.RuleEntity)
                .HasForeignKey(d => d.GameId)
                .HasConstraintName("FK_RuleEntity_GameEntity");
        });

        modelBuilder.Entity<UserEntity>(entity =>
        {
            entity.HasIndex(e => e.Email, "UX_UserEntity_Email").IsUnique();

            entity.Property(e => e.CreatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("sysutcdatetime()");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.UpdatedAt)
                .HasPrecision(3)
                .HasDefaultValueSql("sysutcdatetime()");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}