// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Internal.FantaSottone.Infrastructure.Models;

public partial class GameEntity
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int InitialScore { get; set; }

    public byte Status { get; set; }

    public int? CreatorPlayerId { get; set; }

    public int? WinnerPlayerId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual PlayerEntity CreatorPlayer { get; set; }

    public virtual ICollection<PlayerEntity> PlayerEntity { get; set; } = new List<PlayerEntity>();

    public virtual ICollection<RuleAssignmentEntity> RuleAssignmentEntity { get; set; } = new List<RuleAssignmentEntity>();

    public virtual ICollection<RuleEntity> RuleEntity { get; set; } = new List<RuleEntity>();

    public virtual PlayerEntity WinnerPlayer { get; set; }
}