// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Internal.FantaSottone.Infrastructure.Models;

public partial class PlayerEntity
{
    public int Id { get; set; }

    public int GameId { get; set; }

    public string Username { get; set; }

    public string AccessCode { get; set; }

    public bool IsCreator { get; set; }

    public int CurrentScore { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual GameEntity Game { get; set; }

    public virtual ICollection<GameEntity> GameEntityCreatorPlayer { get; set; } = new List<GameEntity>();

    public virtual ICollection<GameEntity> GameEntityWinnerPlayer { get; set; } = new List<GameEntity>();

    public virtual ICollection<RuleAssignmentEntity> RuleAssignmentEntity { get; set; } = new List<RuleAssignmentEntity>();
}