// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Internal.FantaSottone.Infrastructure.Models;

public partial class RuleEntity
{
    public int Id { get; set; }

    public int GameId { get; set; }

    public string Name { get; set; }

    public byte RuleType { get; set; }

    public int ScoreDelta { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual GameEntity Game { get; set; }

    public virtual RuleAssignmentEntity RuleAssignmentEntity { get; set; }
}