// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Internal.FantaSottone.Infrastructure.Models;

public partial class RuleAssignmentEntity
{
    public int Id { get; set; }

    public int RuleId { get; set; }

    public int GameId { get; set; }

    public int AssignedToPlayerId { get; set; }

    public int ScoreDeltaApplied { get; set; }

    public DateTime AssignedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual PlayerEntity AssignedToPlayer { get; set; }

    public virtual GameEntity Game { get; set; }

    public virtual RuleEntity Rule { get; set; }
}