// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Internal.FantaSottone.Infrastructure.Models;

public partial class UserEntity
{
    public int Id { get; set; }

    public string Email { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<PlayerEntity> PlayerEntity { get; set; } = new List<PlayerEntity>();
}