// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Internal.FantaSottone.Infrastructure.Models;

public partial class vPlayerGameContext
{
    public int UserId { get; set; }

    public string Email { get; set; }

    public int PlayerId { get; set; }

    public int? GameId { get; set; }

    public bool IsCreator { get; set; }

    public int CurrentScore { get; set; }

    public string GameName { get; set; }

    public byte GameStatus { get; set; }

    public int? CreatorPlayerId { get; set; }
}